[tools]
pnpm = "latest"
node = "latest"

[tasks.lint]
description = "Lint with Biome"
run = "pnpm biome lint"

[tasks.format]
description = "Format with Biome"
run = "pnpm biome format"

[tasks.check]
description = "Check .astro/.ts files"
run = "pnpm astro check"

[tasks.pre-commit]
depends = ["lint", "format", "check"]

[tasks.build-dev-image]
description = "Build the development docker image"
run = "docker build -t vni-dev ."

[tasks.run-dev-image]
description = "Run the development docker image"
run = "docker run -it --rm vni-dev"

